FROM php:7.4.22-fpm-alpine3.14

RUN apk add --no-cache $PHPIZE_DEPS bash bash-doc bash-completion sudo openssh libcurl curl curl-dev libzip-dev libxml2-dev libpng-dev \
    && pecl install xdebug opcache \
    && docker-php-ext-install pdo_mysql bcmath ctype curl dom gd hash iconv intl mbstring openssl simplexml soap xsl zip sockets \
    && docker-php-ext-enable xdebug opcache pdo_mysql bcmath ctype curl dom gd hash iconv intl mbstring openssl simplexml soap xsl zip sockets \
    && adduser --uid 1000 --shell /bin/bash --disabled-password --gecos "" web \
    && echo 'web ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

USER web
WORKDIR /data/shared/sites
