name: "x-com"
networks:
  xcom_network:
    driver: bridge
volumes:
  phpsockets:
    driver: local
services:
  nginx:
    image: xcommagento/nginx:1.26.2
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    # restart: always
    hostname: nginx
    ports:
      - 80:80
      - 443:443
    working_dir: /etc/nginx/sites-enabled
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - /Users/frankie/x-com/data/shared/sites:/data/shared/sites
      - phpsockets:/data/shared/sockets
      - /Users/frankie/x-com/data/shared/media:/data/shared/media
      - ~/.config/docker-setup.config:/etc/docker-setup.config:ro
    networks:
      - xcom_network
  redis:
    image: redis:6.2-alpine
    # restart: always
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - xcom_network
  mailtrap:
    image: xcommagento/docker-mailtrap:latest
    # restart: always
    hostname: mailtrap
    ports:
      - 8085:80
      - 0.0.0.0:25:25
    networks:
      - xcom_network
  mailhog:
    image: jcalonso/mailhog
    # restart: always
    hostname: mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - xcom_network
