name: "x-com"
networks:
  xcom_network:
    driver: bridge
services:
  nginx:
    image: xcommagento/docker-nginx:latest
    platform: linux/amd64  # Force AMD64 for compatibility with M1/ARM64
    # restart: always
    hostname: nginx
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    working_dir: /etc/nginx/sites-enabled
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro          # Nginx configuration
      - installdirectory/data/shared/sites:/data/shared/sites      # Web root directories
      - phpsockets:/data/shared/sockets                            # PHP-FPM sockets
      - installdirectory/data/shared/media:/data/shared/media      # Shared media files
      - ~/.config/docker-setup.config:/etc/docker-setup.config:ro  # Configuration file
    networks:
      - xcom_network
  redis:
    image: redis:6.2-alpine
    # restart: always
    hostname: redis
    ports:
      - "6379:6379"  # Redis port
    networks:
      - xcom_network
  mailtrap:
    image: xcommagento/docker-mailtrap:latest
    # restart: always
    hostname: mailtrap
    ports:
      - "8085:80"  # Mailtrap web interface
      - "0.0.0.0:25:25"  # Mailtrap SMTP server
    networks:
      - xcom_network
  mailhog:
    image: jcalonso/mailhog
    # restart: always
    hostname: mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1025:1025"  # Mailhog SMTP server
      - "8025:8025"  # Mailhog web interface
    networks:
      - xcom_network
