#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    echo "No arguments provided"
    docker ps --format '{{.Names}}'
    exit 1
fi

SHELL="/bin/bash";

# check if current user is not in group docker
if ! groups $USER | grep &>/dev/null '\bdocker\b'; then
    # check if current user is not root
    if [ "$EUID" -ne 0 ]; then
        if sudo docker exec -it "docker_$@_1" which zsh >&/dev/null; 
            then SHELL="$(sudo docker exec -it "docker_$@_1" which zsh)";
        fi
        docker exec -it "docker_$@_1" ${SHELL//$'\r'/}
    else
        if sudo docker exec -it "docker_$@_1" which zsh >&/dev/null; 
            then SHELL="$(sudo docker exec -it "docker_$@_1" which zsh)";
        fi
        docker exec -it "docker_$@_1" ${SHELL//$'\r'/}
    fi
else
    if sudo docker exec -it "docker_$@_1" which zsh >&/dev/null; 
        then SHELL="$(sudo docker exec -it "docker_$@_1" which zsh)";
    fi
    docker exec -it "docker_$@_1" ${SHELL//$'\r'/}
fi
