#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    echo "No arguments provided"
    docker ps --format '{{.Names}}'
    exit 1
fi

if ! groups $USER | grep &>/dev/null '\bdocker\b'; then
    if [ "$EUID" -ne 0 ]; then
        sudo docker exec -it "docker_$@_1" /bin/bash
    fi
else
    docker exec -it "docker_$@_1" /bin/bash
fi